// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFf02LO6Ygf9FO4HRja5xj-SX_hWUCjg',
    appId: '1:1002185999075:web:37681f8faf70b33a3dfbd6',
    messagingSenderId: '1002185999075',
    projectId: 'trustguard-ai-2026',
    authDomain: 'trustguard-ai-2026.firebaseapp.com',
    storageBucket: 'trustguard-ai-2026.firebasestorage.app',
    measurementId: 'G-7G1HB0J462',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-E4UyqTraX2r4l9-GUqvJK0LU_CWeNM',
    appId: '1:1002185999075:android:b87c2477b05e510f3dfbd6',
    messagingSenderId: '1002185999075',
    projectId: 'trustguard-ai-2026',
    storageBucket: 'trustguard-ai-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_EmsHmLg-YW9drc34zIqHLobIdimAe8',
    appId: '1:1002185999075:ios:911cd0468dcd52713dfbd6',
    messagingSenderId: '1002185999075',
    projectId: 'trustguard-ai-2026',
    storageBucket: 'trustguard-ai-2026.firebasestorage.app',
    iosClientId: '1002185999075-vtkdiv2h917cp4dbugq7o6g6i9tbvt3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.trustguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_EmsHmLg-YW9drc34zIqHLobIdimAe8',
    appId: '1:1002185999075:ios:911cd0468dcd52713dfbd6',
    messagingSenderId: '1002185999075',
    projectId: 'trustguard-ai-2026',
    storageBucket: 'trustguard-ai-2026.firebasestorage.app',
    iosClientId: '1002185999075-vtkdiv2h917cp4dbugq7o6g6i9tbvt3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.trustguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFf02LO6Ygf9FO4HRja5xj-SX_hWUCjg',
    appId: '1:1002185999075:web:a20317a6c13d22a43dfbd6',
    messagingSenderId: '1002185999075',
    projectId: 'trustguard-ai-2026',
    authDomain: 'trustguard-ai-2026.firebaseapp.com',
    storageBucket: 'trustguard-ai-2026.firebasestorage.app',
    measurementId: 'G-BFBS31VB3Q',
  );
}
